/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.chkpnt.playground.app;

import de.chkpnt.playground.lib1.StringOneProvider;
import de.chkpnt.playground.lib2.StringTwoProvider;

public class App {

    private StringOneProvider oneService = new StringOneProvider();
    private StringTwoProvider twoService = new StringTwoProvider();

    public String getGreeting() {
        return "Hello world: " + oneService.getString() + " " + twoService.getString();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
