/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.chkpnt.playground.app;

import org.hamcrest.CoreMatchers;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.not;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.emptyOrNullString;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    private App sut = new App();

    @Test
    void appHasAGreeting() {
        assertThat(sut.getGreeting(), is(not(emptyOrNullString())));
    }
}
